<a href="https://colab.research.google.com/github/umyunsang/edu/blob/main/ComputerScience/03_ai-ml-data/quantum-ml/work/10_qnn_end_to_end_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Day34 QNN 전체 동작 검증 실습

- Source: Google Drive `Day34/3-10.py`
- Runtime: Google Colab recommended. Do not install or execute dependencies locally for sync validation.


In [1]:
"""
=========================================================
Lab 14

10_summary.py

전체 동작 검증

=========================================================

실습 목표

1. EstimatorQNN 생성 확인

2. TorchConnector 생성 확인

3. Weight 확인

4. Forward 확인

5. Input 변화 확인

6. Weight 변화 확인

7. Gradient 확인

8. Batch 처리 확인

9. Optimizer 확인

=========================================================
"""

import torch
import torch.nn as nn

from create_qnn import create_qnn
from torch_connector import create_torch_connector


# =========================================================
# STEP 1
# Quantum Layer 생성
# =========================================================

print("=" * 70)
print("STEP 1. Quantum Layer")
print("=" * 70)

qnn = create_qnn()
model = create_torch_connector(qnn)

print("Quantum Layer 생성 성공")
print()

# =========================================================
# STEP 2
# Weight 확인
# =========================================================

print("=" * 70)
print("STEP 2. Weight")
print("=" * 70)

print(model.weight)
print()

print("Shape")

print(model.weight.shape)

print()

# =========================================================
# STEP 3
# Forward
# =========================================================

print("=" * 70)
print("STEP 3. Forward")
print("=" * 70)

x = torch.tensor(

    [[0.20,0.70]],

    dtype=torch.float32

)

output = model(x)

print("Input")

print(x)

print()

print("Output")

print(output)

print()

# =========================================================
# STEP 4
# Input 변화
# =========================================================

print("=" * 70)
print("STEP 4. Input Change")
print("=" * 70)

x2 = torch.tensor(

    [[0.80,0.10]],

    dtype=torch.float32

)

output2 = model(x2)

print("Input 1")

print(x)

print()

print("Output 1")

print(output)

print()

print("Input 2")

print(x2)

print()

print("Output 2")

print(output2)

print()

# =========================================================
# STEP 5
# Weight 변화
# =========================================================

print("=" * 70)
print("STEP 5. Weight Change")
print("=" * 70)

backup = model.weight.detach().clone()

before = model(x)

with torch.no_grad():

    model.weight.fill_(0.5)

after = model(x)

print("Before")

print(before)

print()

print("After")

print(after)

print()

with torch.no_grad():

    model.weight.copy_(backup)

# =========================================================
# STEP 6
# Gradient
# =========================================================

print("=" * 70)
print("STEP 6. Gradient")
print("=" * 70)

target = torch.tensor(

    [[1.0]],

    dtype=torch.float32

)

criterion = nn.MSELoss()

prediction = model(x)

loss = criterion(

    prediction,

    target

)

model.zero_grad()

loss.backward()

print(model.weight.grad)

print()

# =========================================================
# STEP 7
# Batch Forward
# =========================================================

print("=" * 70)
print("STEP 7. Batch")
print("=" * 70)

batch = torch.tensor(

    [

        [0.10,0.20],

        [0.30,0.40],

        [0.50,0.60],

        [0.70,0.80]

    ],

    dtype=torch.float32

)

batch_output = model(batch)

print(batch_output)

print()

print("Shape")

print(batch_output.shape)

print()

# =========================================================
# STEP 8
# Optimizer
# =========================================================

print("=" * 70)
print("STEP 8. Optimizer")
print("=" * 70)

optimizer = torch.optim.Adam(

    model.parameters(),

    lr=0.01

)

print(optimizer)

print()

print("Optimizer 연결 완료")

print()

# =========================================================
# STEP 9
# Check List
# =========================================================

print("=" * 70)
print("STEP 9. Check List")
print("=" * 70)

check_list = {

    "EstimatorQNN 생성": True,

    "TorchConnector 생성": True,

    "Weight 확인": True,

    "Forward 실행": True,

    "Input 변화": True,

    "Weight 변화": True,

    "Gradient 생성": model.weight.grad is not None,

    "Batch 처리": batch_output.shape[0] == batch.shape[0],

    "Optimizer 연결": True

}

for key, value in check_list.items():

    print(f"{key:25s} : {'PASS' if value else 'FAIL'}")

print()



STEP 1. Quantum Layer
Quantum Layer 생성 성공

STEP 2. Weight
Parameter containing:
tensor([ 0.8793,  0.5082, -0.1610, -0.4650], requires_grad=True)

Shape
torch.Size([4])

STEP 3. Forward
Input
tensor([[0.2000, 0.7000]])

Output
tensor([[-0.2577]], grad_fn=<_TorchNNFunctionBackward>)

STEP 4. Input Change
Input 1
tensor([[0.2000, 0.7000]])

Output 1
tensor([[-0.2577]], grad_fn=<_TorchNNFunctionBackward>)

Input 2
tensor([[0.8000, 0.1000]])

Output 2
tensor([[0.1572]], grad_fn=<_TorchNNFunctionBackward>)

STEP 5. Weight Change
Before
tensor([[-0.2752]], grad_fn=<_TorchNNFunctionBackward>)

After
tensor([[0.4354]], grad_fn=<_TorchNNFunctionBackward>)

STEP 6. Gradient
tensor([-0.7993, -0.7720, -0.9356, -1.1284])

STEP 7. Batch
tensor([[-0.4416],
        [ 0.0248],
        [-0.3157],
        [-0.0594]], grad_fn=<_TorchNNFunctionBackward>)

Shape
torch.Size([4, 1])

STEP 8. Optimizer


Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

Optimizer 연결 완료

STEP 9. Check List
EstimatorQNN 생성           : PASS
TorchConnector 생성         : PASS
Weight 확인                 : PASS
Forward 실행                : PASS
Input 변화                  : PASS
Weight 변화                 : PASS
Gradient 생성               : PASS
Batch 처리                  : PASS
Optimizer 연결              : PASS

